// Mocks generated by Mockito 5.4.5 from annotations
// in flags_quiz/test/game_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flags_quiz/foundation/asset_provider.dart' as _i2;
import 'package:flags_quiz/foundation/business_logic/quiz_data_provider.dart'
    as _i3;
import 'package:flags_quiz/foundation/random_item_picker.dart' as _i6;
import 'package:flags_quiz/models/country.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAssetProvider_0 extends _i1.SmartFake implements _i2.AssetProvider {
  _FakeAssetProvider_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [QuizDataProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuizDataProvider<T> extends _i1.Mock
    implements _i3.QuizDataProvider<T> {
  @override
  _i2.AssetProvider get provider =>
      (super.noSuchMethod(
            Invocation.getter(#provider),
            returnValue: _FakeAssetProvider_0(
              this,
              Invocation.getter(#provider),
            ),
            returnValueForMissingStub: _FakeAssetProvider_0(
              this,
              Invocation.getter(#provider),
            ),
          )
          as _i2.AssetProvider);

  @override
  T Function(Map<String, dynamic>) get fromJson =>
      (super.noSuchMethod(
            Invocation.getter(#fromJson),
            returnValue:
                (Map<String, dynamic> __p0) =>
                    _i4.dummyValue<T>(this, Invocation.getter(#fromJson)),
            returnValueForMissingStub:
                (Map<String, dynamic> __p0) =>
                    _i4.dummyValue<T>(this, Invocation.getter(#fromJson)),
          )
          as T Function(Map<String, dynamic>));

  @override
  _i5.Future<List<T>> provide() =>
      (super.noSuchMethod(
            Invocation.method(#provide, []),
            returnValue: _i5.Future<List<T>>.value(<T>[]),
            returnValueForMissingStub: _i5.Future<List<T>>.value(<T>[]),
          )
          as _i5.Future<List<T>>);
}

/// A class which mocks [RandomItemPicker].
///
/// See the documentation for Mockito's code generation for more information.
class MockRandomItemPicker extends _i1.Mock
    implements _i6.RandomItemPicker<_i7.Country> {
  @override
  List<_i7.Country> get items =>
      (super.noSuchMethod(
            Invocation.getter(#items),
            returnValue: <_i7.Country>[],
            returnValueForMissingStub: <_i7.Country>[],
          )
          as List<_i7.Country>);

  @override
  int get count =>
      (super.noSuchMethod(
            Invocation.getter(#count),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  void replaceItems(List<_i7.Country>? items) => super.noSuchMethod(
    Invocation.method(#replaceItems, [items]),
    returnValueForMissingStub: null,
  );
}
