# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  # Invoked before lane execution
  before_all do
    update_fastlane
  end  

  desc "Build debug client"
  lane :client_debug do
    gradle(task: "clean bundleDebug")
  end

  desc "Deploy a new version to GooglyPlay,  available tracks 'production, beta, alpha, internal'"
  lane :test_track do |options|
    track = options[:track]
    if !track
      UI.user_error!("Track not passed in parameters")
      next
    end
    android_set_version_code(gradle_file: "app/build.gradle")
    gradle(
      task: "clean bundle",
      build_type: "Release",
      properties: {
        "android.injected.signing.store.file" => ENV["KEYSTORE_PATH"],
        "android.injected.signing.store.password" => ENV["KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["KEY_PASSWORD"],
       }
    )
    upload_to_play_store(track: track)
    commit_version
    push_to_remote
  end

  desc "Commit version bump in repository"
  lane :commit_version do
    begin
      version_code = android_get_version_code
      git_commit(path: "app/build.gradle", message: "VersionCode bump to #{version_code}")
    rescue => ex
      UI.error(ex)
    end
  end

  desc "Push changes to remote repository"
  lane :push_to_remote do
    begin
      push_to_git_remote
    rescue => ex
      UI.error(ex)
    end
  end  	
end
