# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:macos)

platform :macos do
  desc "Submit a new macOS app to the Mac App Store"
  lane :release do
    sh("flutter clean -v")
    sh("flutter build macos --release")

    sh("productbuild --component ../build/macos/Build/Products/Release/flagsquiz.app /Applications --sign 'Developer ID Installer: Your Name (#{ENV['IOS_TEAM_ID']})' --product ../build/macos/Build/Products/Release/flagsquiz.app/Contents/Info.plist ../build/macos/Build/Products/Release/flagsquiz.pkg")

    deliver(
      app_identifier: ENV["MAC_OS_PACKAGE_NAME"],
      pkg: "../build/macos/Build/Products/Release/flagsquiz.pkg",  # Use the .pkg file here
      team_id: ENV["IOS_TEAM_ID"],
      submit_for_review: true,
      automatic_release: false
    )
  end
end
