# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    sh("flutter clean -v")
    sh("flutter build ipa -v")
    upload_to_testflight(team_id: ENV["IOS_TEAM_ID"], ipa: "../build/ios/ipa/flagsquiz.ipa")
  end
end
