name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        run: echo "Flutter is already installed on the self-hosted runner"

      - name: Install dependencies
        run: flutter pub get

      - name: Install lcov
        run: sudo apt-get install -y lcov

      - name: Run tests with coverage
        run: |
          flutter test --coverage
          genhtml coverage/lcov.info -o coverage/html

      - name: Archive test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: coverage/html
          retention-days: 5