name: Deploy macOS

on:
  workflow_dispatch:

jobs:
  macos_deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests with coverage
        run: |
          flutter test --coverage
          genhtml coverage/lcov.info -o coverage/html

      - name: Archive test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: coverage/html
          retention-days: 5

      - name: Deploy macOS
        run: |
          cd macos
          bundle install
          bundle exec fastlane beta
        env:
          MAC_OS_PACKAGE_NAME: ${{ secrets.MAC_OS_PACKAGE_NAME }}