name: Deploy macOS

on:
  workflow_dispatch:

jobs:
  macos_deploy:
    runs-on: self-hosted
    env:
      OSX_APPLE_ID: ${{ secrets.FASTLANE_APPLE_ID }}
      OSX_APP_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
      OSX_TEAM_ID: ${{ secrets.IOS_TEAM_ID }}
      OSX_API_KEY: ${{ secrets.OSX_API_KEY }}
      OSX_API_ISSUER: ${{ secrets.OSX_API_ISSUER }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: flutter pub get

      - name: Build macOS release
        run: |
          flutter clean -v
          flutter build macos --release

      - name: Create .pkg file
        run: |
          productbuild --component "build/macos/Build/Products/Release/flagsquiz.app" /Applications "flagsquiz.pkg"

#      - name: Notarize .pkg (optional)
#        run: |
#          xcrun notarytool submit "flagsquiz.pkg" \
#            --apple-id ${{ env.OSX_APPLE_ID }} \
#            --password ${{ env.OSX_APP_SPECIFIC_PASSWORD }} \
#            --team-id ${{ env.OSX_TEAM_ID }} \
#            --wait
      - name: Save AuthKey file
        run: echo "${{ secrets.OSX_APP_STORE_CONNECT_PRIVATE_KEY }}" > AuthKey_8U392483W2.p8

      - name: Upload to App Store
        run: |
          xcrun altool --upload-app \
            --file "flagsquiz.pkg" \
            --type osx \
            --apiKey ${{ env.OSX_API_KEY }} \
            --apiIssuer ${{ env.OSX_API_ISSUER }} \
            --asc-provider ${{ env.OSX_TEAM_ID }}
